spring.application.name: spring-boot-util-demo
server:
  port: 8088
  context-path: /service

test.file.file_1: /test/test1?name=%s
test.file.file_2: /test/test2
test.url_1: /test/name


logging:
  file: ${user.home}/logs/${HOSTNAME:boxfish}/${spring.application.name}.log
#  level:
#    org.springframework: error
#    org.hibernate: fatal
#    com.boxfishedu: debug

spring.mvc.view.prefix: /WEB-INF/views/
spring.mvc.view.suffix: .jsp