spring.application.name: springBoot-mybatis

spring:
  jpa:
    show-sql: true
    generate-ddl: true
    hibernate.ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL5Dialect
    hibernate.naming.physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
#    配置mysql
  datasource:
    dbcp:
      test-while-idle: true
      validation-query: SELECT 1
    tomcat:
      test-on-connect: true
  jooq:
    sql-dialect: org.hibernate.dialect.MySQL5InnoDBDialect
#mybatis:
#  type-aliases-package: com.testingedu.demos.domain
#  mapper-locations: classpath:/mapper/*.xml

# 其它库
spring.datasource.db2.url: jdbc:mysql://127.0.0.1:3306/lzx?useUnicode=true&characterEncoding=utf-8&useSSL=false
spring.datasource.db2.username: root
spring.datasource.db2.password:
spring.datasource.db2.driver-class-name: com.mysql.jdbc.Driver
spring.datasource.db2.initialSize: 5
spring.datasource.db2.minIdle: 5
spring.datasource.db2.maxActive: 20

# titan库
spring.datasource.titan-master.url: jdbc:mysql://127.0.0.1:3306/bebase?useUnicode=true&characterEncoding=utf-8&useSSL=false
spring.datasource.titan-master.username: root
spring.datasource.titan-master.password:
spring.datasource.titan-master.driver-class-name: com.mysql.jdbc.Driver
spring.datasource.titan-master.initialSize: 5
spring.datasource.titan-master.minIdle: 5
spring.datasource.titan-master.maxActive: 20

##mongo 1库
#basic.mongodb.host: localhost
#basic.mongodb.port: 27017
#basic.mongodb.database: beqp
#basic.mongodb.username: bebase
#basic.mongodb.password:
#
##mongo 2库
#bundle.mongodb.host: localhost
#bundle.mongodb.database: beqp
#bundle.mongodb.username: bebase
#bundle.mongodb.password:

spring.data.mongodb:
  primary:
    host: localhost
    port: 27017
    database: beqp
    username: bebase
    password:

  secondary:
    host: localhost
    port: 27017
    database: test
    username: bebase
    password:
logging:
  file: ${user.home}/logs/${HOSTNAME:log}/${spring.application.name}.log
  level:
    org.springframework: WARN
    com.testingedu.demos: DEBUG
server:
  port: 8099