spring:
  jpa:
    show-sql: true
    generate-ddl: true
    hibernate.ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL5Dialect
    hibernate.naming.physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
#    配置mysql
  datasource:
#    url: jdbc:mysql://127.0.0.1:3306/bebase_cloud?useUnicode=true&characterEncoding=utf-8&useSSL=false
#    username: root
#    password:
#    driver-class-name: com.mysql.jdbc.Driver
    dbcp:
      test-while-idle: true
      validation-query: SELECT 1
    tomcat:
      test-on-connect: true
#      配置mongo
  data:
    mongodb:
      host: localhost
      database: beqp
      username: bebase
      password: boxfish
  jooq:
    sql-dialect: org.hibernate.dialect.MySQL5InnoDBDialect

# 配置 my jdbc
datasource.bebase.url: jdbc:mysql://127.0.0.1:3306/bebase?useUnicode=true&characterEncoding=utf-8&useSSL=false
datasource.bebase.username: root
#datasource.bebase.password:
datasource.bebase.driver-class-name: com.mysql.jdbc.Driver

# 配置 cloud jdbc
datasource.cloud.url: jdbc:mysql://127.0.0.1:3306/lzx?useUnicode=true&characterEncoding=utf-8&useSSL=false
datasource.cloud.username: root
datasource.cloud.password:
datasource.cloud.driver-class-name: com.mysql.jdbc.Driver