server:
  port: 9990
  context-path: /database

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/syj
    username: root
    password:
    driver-class-name: com.mysql.jdbc.Driver
    tomcat:
      test-while-idle: true
      test-on-borrow: true
      validation-query: SELECT 1

  jpa:
     database: MYSQL
     show-sql: true
     generate-ddl: true
     hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy

  resources:
    static-locations: classpath:/templates/
