spring.application.name: springBoot-mybatis

spring:
  jpa:
    show-sql: true
    generate-ddl: true
    hibernate.ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL5Dialect
    hibernate.naming.physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
#    配置mysql
  datasource:
    dbcp:
      test-while-idle: true
      validation-query: SELECT 1
    tomcat:
      test-on-connect: true
  jooq:
    sql-dialect: org.hibernate.dialect.MySQL5InnoDBDialect
mybatis:
  type-aliases-package: com.testingedu.springbootmybatisplus.domain.mysql
  mapper-locations: classpath:/mappers/*.xml


# titan库
spring.datasource.url: jdbc:mysql://127.0.0.1:3306/bebase?useUnicode=true&characterEncoding=utf-8&useSSL=false
spring.datasource.username: root
spring.datasource.password:
spring.datasource.driver-class-name: com.mysql.jdbc.Driver

logging:
  file: ${user.home}/logs/${HOSTNAME:log}/${spring.application.name}.log
  level:
    org.springframework: WARN
    com.testingedu.demos: DEBUG
server:
  port: 8089